package com.zhiyou.hiber002.model;
// Generated 2017-9-6 14:40:31 by Hibernate Tools 5.2.3.Final


import java.util.Date;

/**
 * Customer generated by hbm2java
 */
@SuppressWarnings("serial")
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private Integer customerStateId;
     private Integer customerSourceId;
     private Integer customerCategoryId;
     private Integer userId;
     private String customerName;
     private Boolean customerIsMale;
     private String customerMobile;
     private String customerQq;
     private String customerAddress;
     private String customerEmail;
     private String customerRemark;
     private String customerPosition;
     private String customerBlog;
     private String customerTel;
     private Date customerBirth;
     private String customerCompany;
     private Byte status;
     private String remark;
     private Date createTime;
     private Integer creater;
     private Date updateTime;
     private Integer updater;

    public Customer() {
    }

    public Customer(Integer customerStateId, Integer customerSourceId, Integer customerCategoryId, Integer userId, String customerName, Boolean customerIsMale, String customerMobile, String customerQq, String customerAddress, String customerEmail, String customerRemark, String customerPosition, String customerBlog, String customerTel, Date customerBirth, String customerCompany, Byte status, String remark, Date createTime, Integer creater, Date updateTime, Integer updater) {
       this.customerStateId = customerStateId;
       this.customerSourceId = customerSourceId;
       this.customerCategoryId = customerCategoryId;
       this.userId = userId;
       this.customerName = customerName;
       this.customerIsMale = customerIsMale;
       this.customerMobile = customerMobile;
       this.customerQq = customerQq;
       this.customerAddress = customerAddress;
       this.customerEmail = customerEmail;
       this.customerRemark = customerRemark;
       this.customerPosition = customerPosition;
       this.customerBlog = customerBlog;
       this.customerTel = customerTel;
       this.customerBirth = customerBirth;
       this.customerCompany = customerCompany;
       this.status = status;
       this.remark = remark;
       this.createTime = createTime;
       this.creater = creater;
       this.updateTime = updateTime;
       this.updater = updater;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Integer getCustomerStateId() {
        return this.customerStateId;
    }
    
    public void setCustomerStateId(Integer customerStateId) {
        this.customerStateId = customerStateId;
    }
    public Integer getCustomerSourceId() {
        return this.customerSourceId;
    }
    
    public void setCustomerSourceId(Integer customerSourceId) {
        this.customerSourceId = customerSourceId;
    }
    public Integer getCustomerCategoryId() {
        return this.customerCategoryId;
    }
    
    public void setCustomerCategoryId(Integer customerCategoryId) {
        this.customerCategoryId = customerCategoryId;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public Boolean getCustomerIsMale() {
        return this.customerIsMale;
    }
    
    public void setCustomerIsMale(Boolean customerIsMale) {
        this.customerIsMale = customerIsMale;
    }
    public String getCustomerMobile() {
        return this.customerMobile;
    }
    
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile;
    }
    public String getCustomerQq() {
        return this.customerQq;
    }
    
    public void setCustomerQq(String customerQq) {
        this.customerQq = customerQq;
    }
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }
    public String getCustomerRemark() {
        return this.customerRemark;
    }
    
    public void setCustomerRemark(String customerRemark) {
        this.customerRemark = customerRemark;
    }
    public String getCustomerPosition() {
        return this.customerPosition;
    }
    
    public void setCustomerPosition(String customerPosition) {
        this.customerPosition = customerPosition;
    }
    public String getCustomerBlog() {
        return this.customerBlog;
    }
    
    public void setCustomerBlog(String customerBlog) {
        this.customerBlog = customerBlog;
    }
    public String getCustomerTel() {
        return this.customerTel;
    }
    
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }
    public Date getCustomerBirth() {
        return this.customerBirth;
    }
    
    public void setCustomerBirth(Date customerBirth) {
        this.customerBirth = customerBirth;
    }
    public String getCustomerCompany() {
        return this.customerCompany;
    }
    
    public void setCustomerCompany(String customerCompany) {
        this.customerCompany = customerCompany;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Integer getCreater() {
        return this.creater;
    }
    
    public void setCreater(Integer creater) {
        this.creater = creater;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getUpdater() {
        return this.updater;
    }
    
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }




}


