package com.zhiyou.hiber002.model;
// Generated 2017-9-6 14:40:31 by Hibernate Tools 5.2.3.Final


import java.util.Date;

/**
 * CustomerState generated by hbm2java
 */
public class CustomerState  implements java.io.Serializable {


     private Integer customerStateId;
     private String customerStateName;
     private String customerStateDesc;
     private Byte status;
     private String remark;
     private Date createTime;
     private Integer creater;
     private Date updateTime;
     private Integer updater;

    public CustomerState() {
    }

    public CustomerState(String customerStateName, String customerStateDesc, Byte status, String remark, Date createTime, Integer creater, Date updateTime, Integer updater) {
       this.customerStateName = customerStateName;
       this.customerStateDesc = customerStateDesc;
       this.status = status;
       this.remark = remark;
       this.createTime = createTime;
       this.creater = creater;
       this.updateTime = updateTime;
       this.updater = updater;
    }
   
    public Integer getCustomerStateId() {
        return this.customerStateId;
    }
    
    public void setCustomerStateId(Integer customerStateId) {
        this.customerStateId = customerStateId;
    }
    public String getCustomerStateName() {
        return this.customerStateName;
    }
    
    public void setCustomerStateName(String customerStateName) {
        this.customerStateName = customerStateName;
    }
    public String getCustomerStateDesc() {
        return this.customerStateDesc;
    }
    
    public void setCustomerStateDesc(String customerStateDesc) {
        this.customerStateDesc = customerStateDesc;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Integer getCreater() {
        return this.creater;
    }
    
    public void setCreater(Integer creater) {
        this.creater = creater;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getUpdater() {
        return this.updater;
    }
    
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }




}


