package com.zhiyou.hiber002.model;
// Generated 2017-9-6 14:40:31 by Hibernate Tools 5.2.3.Final


import java.util.Date;

/**
 * CustomerCare generated by hbm2java
 */
public class CustomerCare  implements java.io.Serializable {


     private Integer customerCareId;
     private Integer customerId;
     private String subject;
     private Byte type;
     private Date nextTime;
     private Byte status;
     private String remark;
     private Date createTime;
     private Integer creater;
     private Date updateTime;
     private Integer updater;

    public CustomerCare() {
    }

    public CustomerCare(Integer customerId, String subject, Byte type, Date nextTime, Byte status, String remark, Date createTime, Integer creater, Date updateTime, Integer updater) {
       this.customerId = customerId;
       this.subject = subject;
       this.type = type;
       this.nextTime = nextTime;
       this.status = status;
       this.remark = remark;
       this.createTime = createTime;
       this.creater = creater;
       this.updateTime = updateTime;
       this.updater = updater;
    }
   
    public Integer getCustomerCareId() {
        return this.customerCareId;
    }
    
    public void setCustomerCareId(Integer customerCareId) {
        this.customerCareId = customerCareId;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public Byte getType() {
        return this.type;
    }
    
    public void setType(Byte type) {
        this.type = type;
    }
    public Date getNextTime() {
        return this.nextTime;
    }
    
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Integer getCreater() {
        return this.creater;
    }
    
    public void setCreater(Integer creater) {
        this.creater = creater;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getUpdater() {
        return this.updater;
    }
    
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }




}


