package com.zhiyou.hiber002.model;
// Generated 2017-9-6 14:40:31 by Hibernate Tools 5.2.3.Final


import java.util.Date;

/**
 * CustomerSource generated by hbm2java
 */
public class CustomerSource  implements java.io.Serializable {


     private Integer customerSourceId;
     private String customerSourceName;
     private String customerSourceDesc;
     private Byte status;
     private String remark;
     private Date createTime;
     private Integer creater;
     private Date updateTime;
     private Integer updater;

    public CustomerSource() {
    }

    public CustomerSource(String customerSourceName, String customerSourceDesc, Byte status, String remark, Date createTime, Integer creater, Date updateTime, Integer updater) {
       this.customerSourceName = customerSourceName;
       this.customerSourceDesc = customerSourceDesc;
       this.status = status;
       this.remark = remark;
       this.createTime = createTime;
       this.creater = creater;
       this.updateTime = updateTime;
       this.updater = updater;
    }
   
    public Integer getCustomerSourceId() {
        return this.customerSourceId;
    }
    
    public void setCustomerSourceId(Integer customerSourceId) {
        this.customerSourceId = customerSourceId;
    }
    public String getCustomerSourceName() {
        return this.customerSourceName;
    }
    
    public void setCustomerSourceName(String customerSourceName) {
        this.customerSourceName = customerSourceName;
    }
    public String getCustomerSourceDesc() {
        return this.customerSourceDesc;
    }
    
    public void setCustomerSourceDesc(String customerSourceDesc) {
        this.customerSourceDesc = customerSourceDesc;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Integer getCreater() {
        return this.creater;
    }
    
    public void setCreater(Integer creater) {
        this.creater = creater;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getUpdater() {
        return this.updater;
    }
    
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }




}


