package com.zhiyou.hiber002.model;
// Generated 2017-9-6 14:40:31 by Hibernate Tools 5.2.3.Final


import java.util.Date;

/**
 * CustomerCategory generated by hbm2java
 */
public class CustomerCategory  implements java.io.Serializable {


     private Integer customerCategoryId;
     private String customerCategoryName;
     private String customerCategoryDesc;
     private Byte status;
     private String remark;
     private Date createTime;
     private Integer creater;
     private Date updateTime;
     private Integer updater;

    public CustomerCategory() {
    }

    public CustomerCategory(String customerCategoryName, String customerCategoryDesc, Byte status, String remark, Date createTime, Integer creater, Date updateTime, Integer updater) {
       this.customerCategoryName = customerCategoryName;
       this.customerCategoryDesc = customerCategoryDesc;
       this.status = status;
       this.remark = remark;
       this.createTime = createTime;
       this.creater = creater;
       this.updateTime = updateTime;
       this.updater = updater;
    }
   
    public Integer getCustomerCategoryId() {
        return this.customerCategoryId;
    }
    
    public void setCustomerCategoryId(Integer customerCategoryId) {
        this.customerCategoryId = customerCategoryId;
    }
    public String getCustomerCategoryName() {
        return this.customerCategoryName;
    }
    
    public void setCustomerCategoryName(String customerCategoryName) {
        this.customerCategoryName = customerCategoryName;
    }
    public String getCustomerCategoryDesc() {
        return this.customerCategoryDesc;
    }
    
    public void setCustomerCategoryDesc(String customerCategoryDesc) {
        this.customerCategoryDesc = customerCategoryDesc;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Integer getCreater() {
        return this.creater;
    }
    
    public void setCreater(Integer creater) {
        this.creater = creater;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getUpdater() {
        return this.updater;
    }
    
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }




}


