package com.zhiyou.hiber002.model;
// Generated 2017-9-6 14:40:31 by Hibernate Tools 5.2.3.Final


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer messageId;
     private String subject;
     private String content;
     private Integer sender;
     private Date saveTime;
     private Date sendTime;
     private Integer sendDelete;
     private Integer sendStatus;
     private Date sendUpdateTime;
     private Integer receiver;
     private Integer receiveDelete;
     private Integer receiveStatus;
     private Date receiveUpdateTime;

    public Message() {
    }

    public Message(String subject, String content, Integer sender, Date saveTime, Date sendTime, Integer sendDelete, Integer sendStatus, Date sendUpdateTime, Integer receiver, Integer receiveDelete, Integer receiveStatus, Date receiveUpdateTime) {
       this.subject = subject;
       this.content = content;
       this.sender = sender;
       this.saveTime = saveTime;
       this.sendTime = sendTime;
       this.sendDelete = sendDelete;
       this.sendStatus = sendStatus;
       this.sendUpdateTime = sendUpdateTime;
       this.receiver = receiver;
       this.receiveDelete = receiveDelete;
       this.receiveStatus = receiveStatus;
       this.receiveUpdateTime = receiveUpdateTime;
    }
   
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Integer getSender() {
        return this.sender;
    }
    
    public void setSender(Integer sender) {
        this.sender = sender;
    }
    public Date getSaveTime() {
        return this.saveTime;
    }
    
    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }
    public Integer getSendDelete() {
        return this.sendDelete;
    }
    
    public void setSendDelete(Integer sendDelete) {
        this.sendDelete = sendDelete;
    }
    public Integer getSendStatus() {
        return this.sendStatus;
    }
    
    public void setSendStatus(Integer sendStatus) {
        this.sendStatus = sendStatus;
    }
    public Date getSendUpdateTime() {
        return this.sendUpdateTime;
    }
    
    public void setSendUpdateTime(Date sendUpdateTime) {
        this.sendUpdateTime = sendUpdateTime;
    }
    public Integer getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }
    public Integer getReceiveDelete() {
        return this.receiveDelete;
    }
    
    public void setReceiveDelete(Integer receiveDelete) {
        this.receiveDelete = receiveDelete;
    }
    public Integer getReceiveStatus() {
        return this.receiveStatus;
    }
    
    public void setReceiveStatus(Integer receiveStatus) {
        this.receiveStatus = receiveStatus;
    }
    public Date getReceiveUpdateTime() {
        return this.receiveUpdateTime;
    }
    
    public void setReceiveUpdateTime(Date receiveUpdateTime) {
        this.receiveUpdateTime = receiveUpdateTime;
    }




}


