package com.zhiyou.hiber002.model;
// Generated 2017-9-6 14:40:31 by Hibernate Tools 5.2.3.Final


import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice  implements java.io.Serializable {


     private Integer noticeId;
     private int receiveId;
     private String subject;
     private String text;
     private Date pubTime;
     private Date expireTime;
     private byte status;
     private String remark;
     private Date createTime;
     private int creater;
     private Date updateTime;
     private Integer updater;

    public Notice() {
    }

	
    public Notice(int receiveId, String subject, String text, byte status, Date createTime, int creater) {
        this.receiveId = receiveId;
        this.subject = subject;
        this.text = text;
        this.status = status;
        this.createTime = createTime;
        this.creater = creater;
    }
    public Notice(int receiveId, String subject, String text, Date pubTime, Date expireTime, byte status, String remark, Date createTime, int creater, Date updateTime, Integer updater) {
       this.receiveId = receiveId;
       this.subject = subject;
       this.text = text;
       this.pubTime = pubTime;
       this.expireTime = expireTime;
       this.status = status;
       this.remark = remark;
       this.createTime = createTime;
       this.creater = creater;
       this.updateTime = updateTime;
       this.updater = updater;
    }
   
    public Integer getNoticeId() {
        return this.noticeId;
    }
    
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }
    public int getReceiveId() {
        return this.receiveId;
    }
    
    public void setReceiveId(int receiveId) {
        this.receiveId = receiveId;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getPubTime() {
        return this.pubTime;
    }
    
    public void setPubTime(Date pubTime) {
        this.pubTime = pubTime;
    }
    public Date getExpireTime() {
        return this.expireTime;
    }
    
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public int getCreater() {
        return this.creater;
    }
    
    public void setCreater(int creater) {
        this.creater = creater;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getUpdater() {
        return this.updater;
    }
    
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }




}


