package com.zhiyou.hiber002.model;
// Generated 2017-9-6 14:40:31 by Hibernate Tools 5.2.3.Final


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String password;
     private boolean isAdmin;
     private Boolean isSystem;
     private Integer departmentId;
     private Integer roleId;
     private Boolean isMale;
     private String mobile;
     private String address;
     private Integer age;
     private String tel;
     private String idNum;
     private String email;
     private String qq;
     private String hobby;
     private Byte education;
     private String cardNum;
     private String nation;
     private Byte marry;
     private Byte status;
     private String remark;
     private Date createTime;
     private Integer creater;
     private Date updateTime;
     private Integer updater;

    public User() {
    }

	
    public User(String username, String password, boolean isAdmin) {
        this.username = username;
        this.password = password;
        this.isAdmin = isAdmin;
    }
    public User(String username, String password, boolean isAdmin, Boolean isSystem, Integer departmentId, Integer roleId, Boolean isMale, String mobile, String address, Integer age, String tel, String idNum, String email, String qq, String hobby, Byte education, String cardNum, String nation, Byte marry, Byte status, String remark, Date createTime, Integer creater, Date updateTime, Integer updater) {
       this.username = username;
       this.password = password;
       this.isAdmin = isAdmin;
       this.isSystem = isSystem;
       this.departmentId = departmentId;
       this.roleId = roleId;
       this.isMale = isMale;
       this.mobile = mobile;
       this.address = address;
       this.age = age;
       this.tel = tel;
       this.idNum = idNum;
       this.email = email;
       this.qq = qq;
       this.hobby = hobby;
       this.education = education;
       this.cardNum = cardNum;
       this.nation = nation;
       this.marry = marry;
       this.status = status;
       this.remark = remark;
       this.createTime = createTime;
       this.creater = creater;
       this.updateTime = updateTime;
       this.updater = updater;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Boolean getIsSystem() {
        return this.isSystem;
    }
    
    public void setIsSystem(Boolean isSystem) {
        this.isSystem = isSystem;
    }
    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public Boolean getIsMale() {
        return this.isMale;
    }
    
    public void setIsMale(Boolean isMale) {
        this.isMale = isMale;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getIdNum() {
        return this.idNum;
    }
    
    public void setIdNum(String idNum) {
        this.idNum = idNum;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getQq() {
        return this.qq;
    }
    
    public void setQq(String qq) {
        this.qq = qq;
    }
    public String getHobby() {
        return this.hobby;
    }
    
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }
    public Byte getEducation() {
        return this.education;
    }
    
    public void setEducation(Byte education) {
        this.education = education;
    }
    public String getCardNum() {
        return this.cardNum;
    }
    
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }
    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }
    public Byte getMarry() {
        return this.marry;
    }
    
    public void setMarry(Byte marry) {
        this.marry = marry;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Integer getCreater() {
        return this.creater;
    }
    
    public void setCreater(Integer creater) {
        this.creater = creater;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getUpdater() {
        return this.updater;
    }
    
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }


	@Override
	public String toString() {
		return "User [userId=" + userId + ", username=" + username + ", password=" + password + ", isAdmin=" + isAdmin
				+ ", isSystem=" + isSystem + ", departmentId=" + departmentId + ", roleId=" + roleId + ", isMale="
				+ isMale + ", mobile=" + mobile + ", address=" + address + ", age=" + age + ", tel=" + tel + ", idNum="
				+ idNum + ", email=" + email + ", qq=" + qq + ", hobby=" + hobby + ", education=" + education
				+ ", cardNum=" + cardNum + ", nation=" + nation + ", marry=" + marry + ", status=" + status
				+ ", remark=" + remark + ", createTime=" + createTime + ", creater=" + creater + ", updateTime="
				+ updateTime + ", updater=" + updater + "]";
	}
}


